import Foundation
import os.log

#if canImport(libghostty)
import libghostty

// Per-terminal libghostty surface wrapper (Stage 2 of the rebuild).
//
// Owns one `ghostty_surface_t` on the HOST_MANAGED backend: libghostty does NOT
// spawn a child process — the host streams remote-PTY bytes IN via `feed`
// (`ghostty_surface_write_buffer`) and libghostty hands surface-generated bytes
// (mouse reports, query replies) OUT via the `receive_buffer` callback. Rendering
// is libghostty's own Metal/IOSurface path; the host view drives `draw`
// (`ghostty_surface_draw`) from a CADisplayLink.
//
// The C/idiom layer here is carried forward from the previous implementation
// (it compiled and embodied the hard-won fixes); the crash-prone *view* lifecycle
// was rewritten separately (`GhosttyTerminalView`). Stage 2 renders; real broker
// feed/resize is Stage 3, input is Stage 4, selection is Stage 5.
public final class GhosttySurface {
    private static let log = Logger(subsystem: "sh.conduit.ghostty", category: "surface")

    private var surface: UnsafeMutableRawPointer?
    private var lastSizePx: (width: UInt32, height: UInt32) = (0, 0)

    /// Retained opaque pointer to the host UIView (see init for why it is
    /// *retained*). Released in `teardown()` right after the surface is freed.
    private var hostViewPtr: UnsafeMutableRawPointer?

    /// Surface-generated bytes from libghostty's HOST_MANAGED backend
    /// (`receive_buffer`) — wired to the remote PTY in Stage 4. nil in Stage 2.
    public var onReceiveInput: ((Data) -> Void)?

    /// Strips libghostty's DUPLICATE terminal-query responses (DA/XTVERSION/DSR/…)
    /// before they reach `onReceiveInput`: the broker's real PTY + tmux already
    /// answered them, so libghostty's re-emulated reply is spurious and would
    /// echo as literal `^[[?62;…` text at the prompt. Per-surface so split
    /// sequences reassemble. (Consumed in Stage 4; harmless now.)
    private let queryResponseFilter = QueryResponseFilter()

    public var isAlive: Bool { surface != nil }

    public init(
        hostView: AnyObject?,
        pixelWidth: UInt32 = 0,
        pixelHeight: UInt32 = 0,
        scaleFactor: Double = 2.0,
        fontSize: Float = 10.0
    ) {
        guard let appHandle = GhosttyApp.shared.appHandle else {
            Self.log.error("GhosttySurface init: app not ready")
            return
        }

        var config = ghostty_surface_config_new()
        config.platform_tag = GHOSTTY_PLATFORM_IOS

        // RETAIN the host view for the surface's lifetime (balanced by a release
        // in teardown). libghostty stores this as an UNRETAINED raw pointer in
        // `platform.ios.uiview` + `userdata` and messages it (e.g. `[uiview
        // bounds]`) from its renderer DURING a CoreAnimation commit. With only an
        // unretained pointer, a host view freed before its surface left
        // libghostty messaging freed memory — a `-[… bounds]`-during-CA-commit
        // UAF. Pinning the view alive removes the window regardless of ARC order.
        let uiviewPtr: UnsafeMutableRawPointer?
        if let host = hostView {
            uiviewPtr = Unmanaged.passRetained(host).toOpaque()
        } else {
            uiviewPtr = nil
        }
        config.platform = ghostty_platform_u(ios: ghostty_platform_ios_s(uiview: uiviewPtr))
        config.userdata = uiviewPtr
        config.scale_factor = scaleFactor
        config.font_size = fontSize
        config.backend = GHOSTTY_SURFACE_IO_BACKEND_HOST_MANAGED
        config.receive_userdata = Unmanaged.passUnretained(self).toOpaque()
        config.receive_buffer = { userdata, bytes, len in
            guard let userdata, let bytes, len > 0 else { return }
            let surface = Unmanaged<GhosttySurface>.fromOpaque(userdata).takeUnretainedValue()
            let data = Data(bytes: bytes, count: Int(len))
            // Filter is stateful → hop to main (where it's owned), filter, deliver.
            DispatchQueue.main.async {
                let forwarded = surface.queryResponseFilter.filter(data)
                guard !forwarded.isEmpty else { return }
                surface.onReceiveInput?(forwarded)
            }
        }
        config.receive_resize = { _, _, _, _, _ in }
        config.context = GHOSTTY_SURFACE_CONTEXT_WINDOW

        guard let created: UnsafeMutableRawPointer = ghostty_surface_new(appHandle, &config) else {
            Self.log.error("ghostty_surface_new failed")
            // No surface → teardown never runs to balance passRetained; release here.
            if let p = uiviewPtr { Unmanaged<AnyObject>.fromOpaque(p).release() }
            return
        }
        self.surface = created
        self.hostViewPtr = uiviewPtr

        // Apply the default terminal theme (colors + 16-color palette + a real
        // scrollback so touch-scroll has history) BEFORE the first size so the
        // first frame paints with the right palette. Without this, libghostty
        // renders its built-in defaults (which read as a different, flatter look).
        applyDefaultTheme(fontSize: fontSize)

        // Size immediately so the renderer initializes against a non-zero target
        // (geistty + clauntty both size on creation). Content scale BEFORE size.
        if pixelWidth > 0, pixelHeight > 0 {
            ghostty_surface_set_content_scale(created, scaleFactor, scaleFactor)
            ghostty_surface_set_size(created, pixelWidth, pixelHeight)
            lastSizePx = (pixelWidth, pixelHeight)
        }
        Self.log.info("GhosttySurface created (\(pixelWidth)x\(pixelHeight)@\(scaleFactor))")
    }

    /// Explicit, idempotent teardown. Frees the surface deterministically rather
    /// than relying on ARC deinit ordering vs the host view's CADisplayLink +
    /// CALayer (the `apprt.surface.Mailbox.push` UAF under
    /// `CA::Context::commit_transaction`). Main thread only. Sets `surface = nil`
    /// FIRST so any later draw/feed/resize no-ops, then stands the renderer down,
    /// frees, and drops the host-view retain.
    public func teardown() {
        guard let s = surface else { return }
        surface = nil
        // Stop the renderer before freeing so no queued draw/wakeup fires into a
        // half-freed surface (another `[uiview bounds]`-during-CA-commit window).
        ghostty_surface_set_focus(s, false)
        ghostty_surface_set_occlusion(s, false)
        ghostty_surface_free(s)
        // Surface is freed → libghostty can no longer reach the host view, so
        // drop our retain (balances init's passRetained).
        if let p = hostViewPtr {
            Unmanaged<AnyObject>.fromOpaque(p).release()
        }
        hostViewPtr = nil
    }

    deinit { teardown() }

    /// Forward remote-PTY bytes into libghostty's parser, then tick so the work
    /// flushes and the renderer wakes. Main thread only.
    public func feed(_ bytes: Data) {
        guard let s = surface, !bytes.isEmpty else { return }
        bytes.withUnsafeBytes { (raw: UnsafeRawBufferPointer) in
            guard let base = raw.baseAddress?.assumingMemoryBound(to: UInt8.self) else { return }
            ghostty_surface_write_buffer(s, base, UInt(bytes.count))
        }
        GhosttyApp.shared.tick()
    }

    public func feed(_ string: String) { feed(Data(string.utf8)) }

    // MARK: - Theme

    /// The terminal background color (RGB 0…1), exposed so the host view can paint
    /// the same color behind/around the grid (e.g. the area the keyboard reveals)
    /// instead of pure black. Matches `background` in `themeConfig`.
    public static let backgroundRGB: (red: Double, green: Double, blue: Double) =
        (0x1d / 255.0, 0x1f / 255.0, 0x21 / 255.0)

    /// libghostty config body for our single dark theme (the pre-rebuild look):
    /// `ghosttyDark` palette + a 10 MB scrollback so touch-scroll reveals history.
    /// Line-based `key = value` syntax (matches the reference repos' `ghostty.conf`).
    private static func themeConfig(fontSize: Float) -> String {
        let fs = Int(min(max(fontSize, 6), 32).rounded())
        let palette = [
            "#1d1f21", "#cc6666", "#b5bd68", "#f0c674",
            "#81a2be", "#b294bb", "#8abeb7", "#c5c8c6",
            "#666666", "#d54e53", "#b9ca4a", "#e7c547",
            "#7aa6da", "#c397d8", "#70c0b1", "#eaeaea",
        ]
        var lines = [
            "font-size = \(fs)",
            "scrollback-limit = 10000000",
            "background = #1d1f21",
            "foreground = #c5c8c6",
            "cursor-color = #c5c8c6",
        ]
        for (index, color) in palette.enumerated() {
            lines.append("palette = \(index)=\(color)")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Push the default theme onto the live surface. Our ABI has no
    /// `config_load_string`, so the body is written to a temp `.conf` and loaded
    /// via `ghostty_config_load_file` — the same path the prior wrapper used.
    private func applyDefaultTheme(fontSize: Float) {
        guard let s = surface, let cfg = ghostty_config_new() else { return }
        defer { ghostty_config_free(cfg) }
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("conduit-ghostty-\(UUID().uuidString).conf")
        guard (try? Self.themeConfig(fontSize: fontSize).write(to: url, atomically: true, encoding: .utf8)) != nil
        else { return }
        defer { try? FileManager.default.removeItem(at: url) }
        url.path.withCString { ghostty_config_load_file(cfg, $0) }
        ghostty_config_finalize(cfg)
        ghostty_surface_update_config(s, cfg)
        ghostty_surface_refresh(s)
    }

    /// Push the host view's pixel size + scale (content scale first, then size —
    /// clauntty's order). Cell grid + reflow happen inside libghostty; read the
    /// resulting grid via `gridSize()`.
    public func resize(pixelWidth: UInt32, pixelHeight: UInt32, scale: Double) {
        guard let s = surface else { return }
        guard pixelWidth > 0, pixelHeight > 0 else { return }
        if lastSizePx == (pixelWidth, pixelHeight) { return }
        ghostty_surface_set_content_scale(s, scale, scale)
        ghostty_surface_set_size(s, pixelWidth, pixelHeight)
        lastSizePx = (pixelWidth, pixelHeight)
    }

    /// Render one frame (`ghostty_surface_draw` — our ABI has no `draw_now`).
    /// Driven by the host's CADisplayLink; the wakeup→tick loop is the primary
    /// driver.
    public func draw() {
        guard let s = surface else { return }
        ghostty_surface_draw(s)
    }

    public func refresh() {
        guard let s = surface else { return }
        ghostty_surface_refresh(s)
    }

    /// Pan libghostty's OWN scrollback viewport by a pixel-precise vertical
    /// delta. Used for touch-drag scrolling. The broker runs tmux without the
    /// alternate screen + mouse off, so libghostty keeps real scrollback and
    /// `mouse_scroll` moves the local viewport (nothing is sent to the program).
    /// A POSITIVE delta reveals OLDER content (ghostty maps y>0 to scroll-up), so
    /// the caller passes a positive delta for a finger dragging DOWN. `deltaY` is
    /// in PIXELS (libghostty accumulates a precision scroll against cell height).
    public func scroll(deltaY: Double) {
        guard let s = surface, deltaY != 0 else { return }
        // bit 0 = precision (pixel) flag; momentum phase NONE (active finger drag,
        // not post-release inertia). `ghostty_input_scroll_mods_t` is a packed int.
        let mods: Int32 = 1
        ghostty_surface_mouse_scroll(s, 0, deltaY, mods)
        ghostty_surface_refresh(s)
        GhosttyApp.shared.tick()
    }

    public func setFocus(_ focused: Bool) {
        guard let s = surface else { return }
        ghostty_surface_set_focus(s, focused)
    }

    public func setOcclusion(_ visible: Bool) {
        guard let s = surface else { return }
        ghostty_surface_set_occlusion(s, visible)
    }

    // MARK: - Selection (libghostty-native, driven by host gestures)
    //
    // We forward touch points to libghostty as left-mouse press/drag/release so
    // its own renderer highlights the selection; `readSelection` then returns the
    // selected text for the clipboard. Coordinates are the host view's points
    // (libghostty applies the content scale it was given).

    /// Begin a selection at a point (left-button press).
    public func selectionBegin(x: Double, y: Double) {
        guard let s = surface else { return }
        ghostty_surface_mouse_pos(s, x, y, GHOSTTY_MODS_NONE)
        _ = ghostty_surface_mouse_button(s, GHOSTTY_MOUSE_PRESS, GHOSTTY_MOUSE_LEFT, GHOSTTY_MODS_NONE)
        ghostty_surface_refresh(s)
    }

    /// Select the WORD under a point — a double-click (two press/release pairs at
    /// the same position; libghostty's click counter promotes the second to a
    /// word select). This is the long-press-to-select-a-word entry point; a
    /// subsequent drag extends it.
    public func selectWord(x: Double, y: Double) {
        guard let s = surface else { return }
        ghostty_surface_mouse_pos(s, x, y, GHOSTTY_MODS_NONE)
        _ = ghostty_surface_mouse_button(s, GHOSTTY_MOUSE_PRESS, GHOSTTY_MOUSE_LEFT, GHOSTTY_MODS_NONE)
        _ = ghostty_surface_mouse_button(s, GHOSTTY_MOUSE_RELEASE, GHOSTTY_MOUSE_LEFT, GHOSTTY_MODS_NONE)
        _ = ghostty_surface_mouse_button(s, GHOSTTY_MOUSE_PRESS, GHOSTTY_MOUSE_LEFT, GHOSTTY_MODS_NONE)
        _ = ghostty_surface_mouse_button(s, GHOSTTY_MOUSE_RELEASE, GHOSTTY_MOUSE_LEFT, GHOSTTY_MODS_NONE)
        ghostty_surface_refresh(s)
    }

    /// Extend the selection to a point (drag).
    public func selectionExtend(x: Double, y: Double) {
        guard let s = surface else { return }
        ghostty_surface_mouse_pos(s, x, y, GHOSTTY_MODS_NONE)
        ghostty_surface_refresh(s)
    }

    /// Finish the selection (left-button release).
    public func selectionEnd(x: Double, y: Double) {
        guard let s = surface else { return }
        ghostty_surface_mouse_pos(s, x, y, GHOSTTY_MODS_NONE)
        _ = ghostty_surface_mouse_button(s, GHOSTTY_MOUSE_RELEASE, GHOSTTY_MOUSE_LEFT, GHOSTTY_MODS_NONE)
        ghostty_surface_refresh(s)
    }

    public var hasSelection: Bool {
        guard let s = surface else { return false }
        return ghostty_surface_has_selection(s)
    }

    /// The currently selected text, or nil if there's no selection.
    public func readSelection() -> String? {
        guard let s = surface else { return nil }
        var text = ghostty_text_s()
        guard ghostty_surface_read_selection(s, &text) else { return nil }
        defer { ghostty_surface_free_text(s, &text) }
        guard let ptr = text.text, text.text_len > 0 else { return nil }
        return String(cString: ptr)
    }

    /// The grid libghostty derived from the current pixel size + its own font
    /// metrics (`ghostty_surface_size`) — the authoritative cols/rows the
    /// renderer paints at, which the host must drive the remote PTY to (Stage 3).
    /// nil until libghostty has sized the grid.
    public func gridSize() -> (cols: UInt16, rows: UInt16, cellWidthPx: UInt32, cellHeightPx: UInt32)? {
        guard let s = surface else { return nil }
        let size = ghostty_surface_size(s)
        guard size.columns > 0, size.rows > 0 else { return nil }
        return (size.columns, size.rows, size.cell_width_px, size.cell_height_px)
    }
}

#endif // canImport(libghostty)
