import Foundation

// MARK: - DemoData
//
// Deterministic, in-process fake data powering the App Store reviewer demo mode.
// No network calls, no real broker needed. All timestamps are hardcoded ISO strings
// so output is byte-for-byte reproducible across launches.

enum DemoData {

    // MARK: - Terminal lines
    //
    // Canned faux-terminal output for DemoTerminalView. Each entry is a
    // (isPrompt: Bool, text: String) pair; prompts render in neon.green,
    // output in neon.textDim. Content matches the todo.py narrative so
    // Chat / Terminal / Browser all tell the same story.

    struct TerminalLine {
        let isPrompt: Bool
        let text: String
    }

    static let terminalLines: [TerminalLine] = [
        TerminalLine(isPrompt: true,  text: "python todo.py list"),
        TerminalLine(isPrompt: false, text: "1. [ ] Buy groceries"),
        TerminalLine(isPrompt: false, text: "2. [x] Ship the release"),
        TerminalLine(isPrompt: false, text: "3. [ ] Call the dentist"),
        TerminalLine(isPrompt: true,  text: "python todo.py add \"Review the PR\""),
        TerminalLine(isPrompt: false, text: "Added: Review the PR"),
        TerminalLine(isPrompt: true,  text: "python todo.py list"),
        TerminalLine(isPrompt: false, text: "1. [ ] Buy groceries"),
        TerminalLine(isPrompt: false, text: "2. [x] Ship the release"),
        TerminalLine(isPrompt: false, text: "3. [ ] Call the dentist"),
        TerminalLine(isPrompt: false, text: "4. [ ] Review the PR"),
        TerminalLine(isPrompt: true,  text: "pytest -q"),
        TerminalLine(isPrompt: false, text: "........  [100%]"),
        TerminalLine(isPrompt: false, text: "8 passed in 0.42s"),
        TerminalLine(isPrompt: true,  text: "python todo.py complete 2"),
        TerminalLine(isPrompt: false, text: "Completed: Ship the release"),
        TerminalLine(isPrompt: true,  text: "git add todo.py && git commit -m \"feat: add todo CLI\""),
        TerminalLine(isPrompt: false, text: "[main 4f2a1c3] feat: add todo CLI"),
        TerminalLine(isPrompt: false, text: " 1 file changed, 47 insertions(+)"),
    ]

    // MARK: - Sessions

    static let sessions: [ProjectSession] = [
        ProjectSession(
            id: "demo-session-1",
            name: "demo-session-1",
            assistant: "claude",
            branch: nil,
            preview: nil,
            reasoningEffort: nil,
            cwd: "/home/user/projects/todo",
            startedAt: "2026-06-25T10:00:00Z",
            lastActivityAt: "2026-06-25T10:03:30Z",
            displayName: "Build a to-do app",
            totalInputTokens: 120_000,
            totalOutputTokens: 18_000,
            totalCachedTokens: 90_000,
            totalCostUsd: 0.42,
            contextUsedTokens: 48_000,
            contextWindowTokens: 200_000
        ),
        ProjectSession(
            id: "demo-session-2",
            name: "demo-session-2",
            assistant: "claude",
            branch: nil,
            preview: nil,
            reasoningEffort: nil,
            cwd: "/home/user/projects/api",
            startedAt: "2026-06-25T09:30:00Z",
            lastActivityAt: "2026-06-25T09:35:00Z",
            displayName: "Fix authentication bug",
            totalInputTokens: 34_000,
            totalOutputTokens: 5_200,
            totalCachedTokens: 22_000,
            totalCostUsd: 0.11,
            contextUsedTokens: 12_000,
            contextWindowTokens: 200_000
        ),
    ]

    // MARK: - Canned SessionStatus for demo sessions
    //
    // Seeded into store.statusBySession by activateDemo() so Usage/Recap/Activity
    // screens light up. Values are consistent with the session usage fields above.

    static let statusBySession: [String: SessionStatus] = [
        "demo-session-1": SessionStatus(
            session: "demo-session-1",
            assistant: "claude",
            phase: "idle",
            health: "green",
            rows: 40,
            cols: 120,
            yolo: false,
            preview: nil,
            sessionName: "demo-session-1",
            viewers: 1,
            reasoningEffort: nil,
            cwd: "/home/user/projects/todo",
            startedAt: "2026-06-25T10:00:00Z",
            lastActivityAt: "2026-06-25T10:03:30Z",
            displayName: "Build a to-do app",
            totalInputTokens: 120_000,
            totalOutputTokens: 18_000,
            totalCachedTokens: 90_000,
            totalCostUsd: 0.42,
            contextUsedTokens: 48_000,
            contextWindowTokens: 200_000
        ),
        "demo-session-2": SessionStatus(
            session: "demo-session-2",
            assistant: "claude",
            phase: "idle",
            health: "green",
            rows: 40,
            cols: 120,
            yolo: false,
            preview: nil,
            sessionName: "demo-session-2",
            viewers: 1,
            reasoningEffort: nil,
            cwd: "/home/user/projects/api",
            startedAt: "2026-06-25T09:30:00Z",
            lastActivityAt: "2026-06-25T09:35:00Z",
            displayName: "Fix authentication bug",
            totalInputTokens: 34_000,
            totalOutputTokens: 5_200,
            totalCachedTokens: 22_000,
            totalCostUsd: 0.11,
            contextUsedTokens: 12_000,
            contextWindowTokens: 200_000
        ),
    ]

    // MARK: - Conversations

    static let conversationBySession: [String: [ConversationItem]] = [
        "demo-session-1": session1Conversation,
        "demo-session-2": session2Conversation,
    ]

    // MARK: Session 1: Build a to-do app

    private static let session1Conversation: [ConversationItem] = [
        ConversationItem(
            id: "demo-1-1",
            role: "user",
            kind: "message",
            status: "done",
            content: "Build me a simple to-do list app in Python",
            ts: "2026-06-25T10:00:00Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-2",
            role: "assistant",
            kind: "message",
            status: "done",
            content: "I'll create a clean command-line to-do app. Let me start by creating the file.",
            ts: "2026-06-25T10:00:05Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-3",
            role: "tool",
            kind: "tool",
            status: "done",
            content: "",
            ts: "2026-06-25T10:00:10Z",
            files: [],
            toolName: "bash",
            command: "python3 -c \"open('todo.py','w').write('...')\"",
            exitCode: 0,
            durationMs: 350,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-4",
            role: "tool",
            kind: "tool",
            status: "done",
            content: "",
            ts: "2026-06-25T10:00:15Z",
            files: [],
            toolName: "str_replace_based_edit_tool",
            command: "Write todo.py",
            exitCode: 0,
            durationMs: 120,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-5",
            role: "assistant",
            kind: "message",
            status: "done",
            content: "Done! I've created `todo.py` with `add`, `list`, `complete`, and `delete` commands. Try it with:\n\n```\npython todo.py add 'Buy groceries'\npython todo.py list\n```",
            ts: "2026-06-25T10:00:20Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-6",
            role: "user",
            kind: "message",
            status: "done",
            content: "Can you add colored output?",
            ts: "2026-06-25T10:02:00Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-7",
            role: "assistant",
            kind: "message",
            status: "done",
            content: "Sure, I'll use `colorama` for cross-platform color support.",
            ts: "2026-06-25T10:02:05Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-8",
            role: "tool",
            kind: "tool",
            status: "done",
            content: "Collecting colorama\n  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)\nSuccessfully installed colorama-0.4.6",
            ts: "2026-06-25T10:02:10Z",
            files: [],
            toolName: "bash",
            command: "pip install colorama",
            exitCode: 0,
            durationMs: 1200,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-9",
            role: "tool",
            kind: "tool",
            status: "done",
            content: "",
            ts: "2026-06-25T10:02:15Z",
            files: [],
            toolName: "str_replace_based_edit_tool",
            command: "Update todo.py with colorama",
            exitCode: 0,
            durationMs: 90,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-1-10",
            role: "assistant",
            kind: "message",
            status: "done",
            content: "Updated! Pending tasks now show in yellow, completed ones in green. Run `python todo.py list` to see it.",
            ts: "2026-06-25T10:02:20Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        // CODE: assistant message with a python fenced block
        ConversationItem(
            id: "demo-1-11",
            role: "assistant",
            kind: "message",
            status: "done",
            content: "Here is the key section of `todo.py` that handles color output:\n\n```python\nfrom colorama import Fore, Style, init\ninit(autoreset=True)\n\ndef list_tasks(tasks):\n    for i, task in enumerate(tasks, 1):\n        if task['done']:\n            print(f\"{Fore.GREEN}{i}. [x] {task['text']}{Style.RESET_ALL}\")\n        else:\n            print(f\"{Fore.YELLOW}{i}. [ ] {task['text']}{Style.RESET_ALL}\")\n```",
            ts: "2026-06-25T10:02:30Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        // DIFF: unified diff of the colorama edit
        ConversationItem(
            id: "demo-1-12",
            role: "tool",
            kind: "diff",
            status: "done",
            content: "--- a/todo.py\n+++ b/todo.py\n@@ -1,5 +1,11 @@\n+from colorama import Fore, Style, init\n+init(autoreset=True)\n+\n import json, sys\n \n def list_tasks(tasks):\n-    for i, task in enumerate(tasks, 1):\n-        print(f\"{i}. {'[x]' if task['done'] else '[ ]'} {task['text']}\")\n+    for i, task in enumerate(tasks, 1):\n+        if task['done']:\n+            print(f\"{Fore.GREEN}{i}. [x] {task['text']}{Style.RESET_ALL}\")\n+        else:\n+            print(f\"{Fore.YELLOW}{i}. [ ] {task['text']}{Style.RESET_ALL}\")",
            ts: "2026-06-25T10:02:35Z",
            files: [],
            toolName: "str_replace_based_edit_tool",
            command: nil,
            exitCode: 0,
            durationMs: 90,
            diffSummary: "1 file · +6 -1",
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        // PENDING-INPUT: assistant asking if user wants unit tests
        ConversationItem(
            id: "demo-1-13",
            role: "assistant",
            kind: "pending_input",
            status: "pending",
            content: "Want me to add unit tests for the CLI commands?",
            ts: "2026-06-25T10:03:00Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: ["Add tests", "Not now"],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
    ]

    // MARK: Session 2: Fix authentication bug

    private static let session2Conversation: [ConversationItem] = [
        ConversationItem(
            id: "demo-2-1",
            role: "user",
            kind: "message",
            status: "done",
            content: "My login endpoint returns 401 even with correct credentials",
            ts: "2026-06-25T09:30:00Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-2-2",
            role: "assistant",
            kind: "message",
            status: "done",
            content: "Let me look at the auth code.",
            ts: "2026-06-25T09:30:05Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-2-3",
            role: "tool",
            kind: "tool",
            status: "done",
            content: "src/auth.py:47:    if token.expires_at >= now:",
            ts: "2026-06-25T09:30:10Z",
            files: [],
            toolName: "bash",
            command: "grep -r 'expired_at\\|token' src/auth.py",
            exitCode: 0,
            durationMs: 180,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-2-4",
            role: "assistant",
            kind: "message",
            status: "done",
            content: "Found it -- line 47 uses `>=` instead of `>`, so tokens are rejected exactly at their stated expiry rather than after. Let me fix it.",
            ts: "2026-06-25T09:30:15Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-2-5",
            role: "tool",
            kind: "tool",
            status: "done",
            content: "",
            ts: "2026-06-25T09:30:20Z",
            files: [],
            toolName: "str_replace_based_edit_tool",
            command: "Fix auth.py:47 >= to >",
            exitCode: 0,
            durationMs: 80,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        ConversationItem(
            id: "demo-2-6",
            role: "assistant",
            kind: "message",
            status: "done",
            content: "Fixed. The comparison is now `> expires_at` instead of `>= expires_at`. Tokens will now be accepted up to and including their expiry second.",
            ts: "2026-06-25T09:30:25Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        // PLAN: checklist for the full fix
        ConversationItem(
            id: "demo-2-7",
            role: "assistant",
            kind: "plan",
            status: "done",
            content: "Here is the plan for the full token-refresh fix:",
            ts: "2026-06-25T09:30:30Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: [
                PlanStep(text: "reproduce the 401 loop", state: "done"),
                PlanStep(text: "add backoff on refresh", state: "done"),
                PlanStep(text: "add a regression test", state: "todo"),
            ]
        ),
        // SUBAGENT: audit of refreshToken callers
        ConversationItem(
            id: "demo-2-8",
            role: "system",
            kind: "subagent",
            status: "done",
            content: "subagent: audited callers of refreshToken()\nFound 3 call sites; 2 guarded, 1 missing the 401 backoff.",
            ts: "2026-06-25T09:31:00Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: nil,
            targetAgent: nil,
            taskText: nil,
            resultSummary: nil,
            planSteps: []
        ),
        // HANDOFF: claude -> codex to port fix to mobile
        ConversationItem(
            id: "demo-2-9",
            role: "assistant",
            kind: "handoff",
            status: "done",
            content: "Refresh loop fixed; 401s now back off. Handing the mobile port to codex.",
            ts: "2026-06-25T09:31:30Z",
            files: [],
            toolName: nil,
            command: nil,
            exitCode: nil,
            durationMs: nil,
            diffSummary: nil,
            pendingOptions: [],
            sourceAgent: "claude",
            targetAgent: "codex",
            taskText: "Port the token-refresh fix to the mobile client",
            resultSummary: "Refresh loop fixed; 401s now back off. Handing the mobile port to codex.",
            planSteps: []
        ),
    ]
}
