package sh.nikhil.conduit.demo

import uniffi.conduit_core.ConversationItem
import uniffi.conduit_core.ProjectSession

/**
 * Deterministic, in-process fake data for the App Store reviewer demo mode.
 * No network calls, no real broker needed. All timestamps are hardcoded ISO
 * strings so output is byte-for-byte reproducible across launches.
 */
object DemoData {

    // -------------------------------------------------------------------------
    // Sessions
    // -------------------------------------------------------------------------

    val sessions: List<ProjectSession> = listOf(
        ProjectSession(
            id = "demo-session-1",
            name = "demo-session-1",
            assistant = "claude",
            branch = null,
            preview = null,
            reasoningEffort = null,
            cwd = "/home/user/projects/todo",
            startedAt = "2026-06-25T10:00:00Z",
            lastActivityAt = "2026-06-25T10:03:30Z",
            displayName = "Build a to-do app",
            totalInputTokens = null,
            totalOutputTokens = null,
            totalCachedTokens = null,
            totalCostUsd = null,
            contextUsedTokens = null,
            contextWindowTokens = null,
        ),
        ProjectSession(
            id = "demo-session-2",
            name = "demo-session-2",
            assistant = "claude",
            branch = null,
            preview = null,
            reasoningEffort = null,
            cwd = "/home/user/projects/api",
            startedAt = "2026-06-25T09:30:00Z",
            lastActivityAt = "2026-06-25T09:35:00Z",
            displayName = "Fix authentication bug",
            totalInputTokens = null,
            totalOutputTokens = null,
            totalCachedTokens = null,
            totalCostUsd = null,
            contextUsedTokens = null,
            contextWindowTokens = null,
        ),
    )

    // -------------------------------------------------------------------------
    // Session 1: Build a to-do app
    // -------------------------------------------------------------------------

    private val session1Conversation: List<ConversationItem> = listOf(
        ConversationItem(
            id = "demo-1-1",
            role = "user",
            kind = "message",
            status = "done",
            content = "Build me a simple to-do list app in Python",
            ts = "2026-06-25T10:00:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-2",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "I'll create a clean command-line to-do app. Let me start by creating the file.",
            ts = "2026-06-25T10:00:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-3",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:00:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "python3 -c \"open('todo.py','w').write('...')\"",
            exitCode = 0,
            durationMs = 350UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-4",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:00:15Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Write todo.py",
            exitCode = 0,
            durationMs = 120UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-5",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Done! I've created `todo.py` with `add`, `list`, `complete`, and `delete` commands. Try it with:\n\n```\npython todo.py add 'Buy groceries'\npython todo.py list\n```",
            ts = "2026-06-25T10:00:20Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-6",
            role = "user",
            kind = "message",
            status = "done",
            content = "Can you add colored output?",
            ts = "2026-06-25T10:02:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-7",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Sure, I'll use `colorama` for cross-platform color support.",
            ts = "2026-06-25T10:02:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-8",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "Collecting colorama\n  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)\nSuccessfully installed colorama-0.4.6",
            ts = "2026-06-25T10:02:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "pip install colorama",
            exitCode = 0,
            durationMs = 1200UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-9",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:02:15Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Update todo.py with colorama",
            exitCode = 0,
            durationMs = 90UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-10",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Updated! Pending tasks now show in yellow, completed ones in green. Run `python todo.py list` to see it.",
            ts = "2026-06-25T10:02:20Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
    )

    // -------------------------------------------------------------------------
    // Session 2: Fix authentication bug
    // -------------------------------------------------------------------------

    private val session2Conversation: List<ConversationItem> = listOf(
        ConversationItem(
            id = "demo-2-1",
            role = "user",
            kind = "message",
            status = "done",
            content = "My login endpoint returns 401 even with correct credentials",
            ts = "2026-06-25T09:30:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-2",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Let me look at the auth code.",
            ts = "2026-06-25T09:30:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-3",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "src/auth.py:47:    if token.expires_at >= now:",
            ts = "2026-06-25T09:30:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "grep -r 'expired_at\\|token' src/auth.py",
            exitCode = 0,
            durationMs = 180UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-4",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Found it -- line 47 uses `>=` instead of `>`, so tokens are rejected exactly at their stated expiry rather than after. Let me fix it.",
            ts = "2026-06-25T09:30:15Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-5",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T09:30:20Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Fix auth.py:47 >= to >",
            exitCode = 0,
            durationMs = 80UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-6",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Fixed. The comparison is now `> expires_at` instead of `>= expires_at`. Tokens will now be accepted up to and including their expiry second.",
            ts = "2026-06-25T09:30:25Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
    )

    // -------------------------------------------------------------------------
    // Conversations keyed by session id (declared after the lists to respect
    // Kotlin object-property initialization order — referencing them above
    // would read uninitialized nulls and cause a compile error).
    // -------------------------------------------------------------------------

    val conversationBySession: Map<String, List<ConversationItem>> = mapOf(
        "demo-session-1" to session1Conversation,
        "demo-session-2" to session2Conversation,
    )
}
