package sh.nikhil.conduit.demo

import uniffi.conduit_core.ConversationItem
import uniffi.conduit_core.PlanStep
import uniffi.conduit_core.ProjectSession

/**
 * Deterministic, in-process fake data for the App Store reviewer demo mode.
 * No network calls, no real broker needed. All timestamps are hardcoded ISO
 * strings so output is byte-for-byte reproducible across launches.
 */
object DemoData {

    // -------------------------------------------------------------------------
    // Terminal lines
    //
    // Canned faux-terminal output for DemoTerminalPage. Each entry is a
    // TerminalLine(isPrompt, text); prompts render in neon.green, output
    // in neon.textDim. Mirrors iOS DemoData.terminalLines value-for-value.
    // -------------------------------------------------------------------------

    data class TerminalLine(val isPrompt: Boolean, val text: String)

    val terminalLines: List<TerminalLine> = listOf(
        TerminalLine(isPrompt = true,  text = "python todo.py list"),
        TerminalLine(isPrompt = false, text = "1. [ ] Buy groceries"),
        TerminalLine(isPrompt = false, text = "2. [x] Ship the release"),
        TerminalLine(isPrompt = false, text = "3. [ ] Call the dentist"),
        TerminalLine(isPrompt = true,  text = "python todo.py add \"Review the PR\""),
        TerminalLine(isPrompt = false, text = "Added: Review the PR"),
        TerminalLine(isPrompt = true,  text = "python todo.py list"),
        TerminalLine(isPrompt = false, text = "1. [ ] Buy groceries"),
        TerminalLine(isPrompt = false, text = "2. [x] Ship the release"),
        TerminalLine(isPrompt = false, text = "3. [ ] Call the dentist"),
        TerminalLine(isPrompt = false, text = "4. [ ] Review the PR"),
        TerminalLine(isPrompt = true,  text = "pytest -q"),
        TerminalLine(isPrompt = false, text = "........  [100%]"),
        TerminalLine(isPrompt = false, text = "8 passed in 0.42s"),
        TerminalLine(isPrompt = true,  text = "python todo.py complete 2"),
        TerminalLine(isPrompt = false, text = "Completed: Ship the release"),
        TerminalLine(isPrompt = true,  text = "git add todo.py && git commit -m \"feat: add todo CLI\""),
        TerminalLine(isPrompt = false, text = "[main 4f2a1c3] feat: add todo CLI"),
        TerminalLine(isPrompt = false, text = " 1 file changed, 47 insertions(+)"),
    )

    // -------------------------------------------------------------------------
    // Sessions
    // -------------------------------------------------------------------------

    val sessions: List<ProjectSession> = listOf(
        ProjectSession(
            id = "demo-session-1",
            name = "demo-session-1",
            assistant = "claude",
            branch = null,
            preview = null,
            reasoningEffort = null,
            cwd = "/home/user/projects/todo",
            startedAt = "2026-06-25T10:00:00Z",
            lastActivityAt = "2026-06-25T10:03:30Z",
            displayName = "Build a to-do app",
            totalInputTokens = null,
            totalOutputTokens = null,
            totalCachedTokens = null,
            totalCostUsd = null,
            contextUsedTokens = null,
            contextWindowTokens = null,
        ),
        ProjectSession(
            id = "demo-session-2",
            name = "demo-session-2",
            assistant = "claude",
            branch = null,
            preview = null,
            reasoningEffort = null,
            cwd = "/home/user/projects/api",
            startedAt = "2026-06-25T09:30:00Z",
            lastActivityAt = "2026-06-25T09:35:00Z",
            displayName = "Fix authentication bug",
            totalInputTokens = null,
            totalOutputTokens = null,
            totalCachedTokens = null,
            totalCostUsd = null,
            contextUsedTokens = null,
            contextWindowTokens = null,
        ),
    )

    // -------------------------------------------------------------------------
    // Session 1: Build a to-do app
    // -------------------------------------------------------------------------

    private val session1Conversation: List<ConversationItem> = listOf(
        ConversationItem(
            id = "demo-1-1",
            role = "user",
            kind = "message",
            status = "done",
            content = "Build me a simple to-do list app in Python",
            ts = "2026-06-25T10:00:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-2",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "I'll create a clean command-line to-do app. Let me start by creating the file.",
            ts = "2026-06-25T10:00:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-3",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:00:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "python3 -c \"open('todo.py','w').write('...')\"",
            exitCode = 0,
            durationMs = 350UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-4",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:00:15Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Write todo.py",
            exitCode = 0,
            durationMs = 120UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-5",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Done! I've created `todo.py` with `add`, `list`, `complete`, and `delete` commands. Try it with:\n\n```\npython todo.py add 'Buy groceries'\npython todo.py list\n```",
            ts = "2026-06-25T10:00:20Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-6",
            role = "user",
            kind = "message",
            status = "done",
            content = "Can you add colored output?",
            ts = "2026-06-25T10:02:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-7",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Sure, I'll use `colorama` for cross-platform color support.",
            ts = "2026-06-25T10:02:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-8",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "Collecting colorama\n  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)\nSuccessfully installed colorama-0.4.6",
            ts = "2026-06-25T10:02:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "pip install colorama",
            exitCode = 0,
            durationMs = 1200UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-9",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:02:15Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Update todo.py with colorama",
            exitCode = 0,
            durationMs = 90UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-10",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Updated! Pending tasks now show in yellow, completed ones in green. Run `python todo.py list` to see it.",
            ts = "2026-06-25T10:02:20Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // CODE: assistant message with a python fenced block
        ConversationItem(
            id = "demo-1-11",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Here is the key section of `todo.py` that handles color output:\n\n```python\nfrom colorama import Fore, Style, init\ninit(autoreset=True)\n\ndef list_tasks(tasks):\n    for i, task in enumerate(tasks, 1):\n        if task['done']:\n            print(f\"{Fore.GREEN}{i}. [x] {task['text']}{Style.RESET_ALL}\")\n        else:\n            print(f\"{Fore.YELLOW}{i}. [ ] {task['text']}{Style.RESET_ALL}\")\n```",
            ts = "2026-06-25T10:02:30Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // DIFF: unified diff of the colorama edit
        ConversationItem(
            id = "demo-1-12",
            role = "tool",
            kind = "diff",
            status = "done",
            content = "--- a/todo.py\n+++ b/todo.py\n@@ -1,5 +1,11 @@\n+from colorama import Fore, Style, init\n+init(autoreset=True)\n+\n import json, sys\n \n def list_tasks(tasks):\n-    for i, task in enumerate(tasks, 1):\n-        print(f\"{i}. {'[x]' if task['done'] else '[ ]'} {task['text']}\")\n+    for i, task in enumerate(tasks, 1):\n+        if task['done']:\n+            print(f\"{Fore.GREEN}{i}. [x] {task['text']}{Style.RESET_ALL}\")\n+        else:\n+            print(f\"{Fore.YELLOW}{i}. [ ] {task['text']}{Style.RESET_ALL}\")",
            ts = "2026-06-25T10:02:35Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = null,
            exitCode = 0,
            durationMs = 90UL,
            diffSummary = "1 file · +6 -1",
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // PENDING-INPUT: assistant asking if user wants unit tests
        ConversationItem(
            id = "demo-1-13",
            role = "assistant",
            kind = "pending_input",
            status = "pending",
            content = "Want me to add unit tests for the CLI commands?",
            ts = "2026-06-25T10:03:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = listOf("Add tests", "Not now"),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
    )

    // -------------------------------------------------------------------------
    // Session 2: Fix authentication bug
    // -------------------------------------------------------------------------

    private val session2Conversation: List<ConversationItem> = listOf(
        ConversationItem(
            id = "demo-2-1",
            role = "user",
            kind = "message",
            status = "done",
            content = "My login endpoint returns 401 even with correct credentials",
            ts = "2026-06-25T09:30:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-2",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Let me look at the auth code.",
            ts = "2026-06-25T09:30:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-3",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "src/auth.py:47:    if token.expires_at >= now:",
            ts = "2026-06-25T09:30:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "grep -r 'expired_at\\|token' src/auth.py",
            exitCode = 0,
            durationMs = 180UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-4",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Found it -- line 47 uses `>=` instead of `>`, so tokens are rejected exactly at their stated expiry rather than after. Let me fix it.",
            ts = "2026-06-25T09:30:15Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-5",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T09:30:20Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Fix auth.py:47 >= to >",
            exitCode = 0,
            durationMs = 80UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-6",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Fixed. The comparison is now `> expires_at` instead of `>= expires_at`. Tokens will now be accepted up to and including their expiry second.",
            ts = "2026-06-25T09:30:25Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // PLAN: checklist for the full fix
        ConversationItem(
            id = "demo-2-7",
            role = "assistant",
            kind = "plan",
            status = "done",
            content = "Here is the plan for the full token-refresh fix:",
            ts = "2026-06-25T09:30:30Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = listOf(
                PlanStep(text = "reproduce the 401 loop", state = "done"),
                PlanStep(text = "add backoff on refresh", state = "done"),
                PlanStep(text = "add a regression test", state = "todo"),
            ),
        ),
        // SUBAGENT: audit of refreshToken callers
        ConversationItem(
            id = "demo-2-8",
            role = "system",
            kind = "subagent",
            status = "done",
            content = "subagent: audited callers of refreshToken()\nFound 3 call sites; 2 guarded, 1 missing the 401 backoff.",
            ts = "2026-06-25T09:31:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // HANDOFF: claude -> codex to port fix to mobile
        ConversationItem(
            id = "demo-2-9",
            role = "assistant",
            kind = "handoff",
            status = "done",
            content = "Refresh loop fixed; 401s now back off. Handing the mobile port to codex.",
            ts = "2026-06-25T09:31:30Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = "claude",
            targetAgent = "codex",
            taskText = "Port the token-refresh fix to the mobile client",
            resultSummary = "Refresh loop fixed; 401s now back off. Handing the mobile port to codex.",
            planSteps = emptyList(),
        ),
    )

    // -------------------------------------------------------------------------
    // Conversations keyed by session id (declared after the lists to respect
    // Kotlin object-property initialization order — referencing them above
    // would read uninitialized nulls and cause a compile error).
    // -------------------------------------------------------------------------

    val conversationBySession: Map<String, List<ConversationItem>> = mapOf(
        "demo-session-1" to session1Conversation,
        "demo-session-2" to session2Conversation,
    )
}
