package sh.nikhil.conduit.demo

import sh.nikhil.conduit.ui.Pipeline
import sh.nikhil.conduit.ui.PipelineGate
import sh.nikhil.conduit.ui.PipelineStep
import sh.nikhil.conduit.ui.PipelineSummary
import sh.nikhil.conduit.ui.PipelineSummaryStep
import uniffi.conduit_core.ConversationItem
import uniffi.conduit_core.PlanStep
import uniffi.conduit_core.ProjectSession
import uniffi.conduit_core.SessionStatus

/**
 * Deterministic, in-process fake data for the App Store reviewer demo mode.
 * No network calls, no real broker needed. All timestamps are hardcoded ISO
 * strings so output is byte-for-byte reproducible across launches.
 */
object DemoData {

    // -------------------------------------------------------------------------
    // Terminal lines
    //
    // Canned faux-terminal output for DemoTerminalPage. Each entry is a
    // TerminalLine(isPrompt, text); prompts render in neon.green, output
    // in neon.textDim. Mirrors iOS DemoData.terminalLines value-for-value.
    // -------------------------------------------------------------------------

    data class TerminalLine(val isPrompt: Boolean, val text: String)

    val terminalLines: List<TerminalLine> = listOf(
        TerminalLine(isPrompt = true,  text = "python todo.py list"),
        TerminalLine(isPrompt = false, text = "1. [ ] Buy groceries"),
        TerminalLine(isPrompt = false, text = "2. [x] Ship the release"),
        TerminalLine(isPrompt = false, text = "3. [ ] Call the dentist"),
        TerminalLine(isPrompt = true,  text = "python todo.py add \"Review the PR\""),
        TerminalLine(isPrompt = false, text = "Added: Review the PR"),
        TerminalLine(isPrompt = true,  text = "python todo.py list"),
        TerminalLine(isPrompt = false, text = "1. [ ] Buy groceries"),
        TerminalLine(isPrompt = false, text = "2. [x] Ship the release"),
        TerminalLine(isPrompt = false, text = "3. [ ] Call the dentist"),
        TerminalLine(isPrompt = false, text = "4. [ ] Review the PR"),
        TerminalLine(isPrompt = true,  text = "pytest -q"),
        TerminalLine(isPrompt = false, text = "........  [100%]"),
        TerminalLine(isPrompt = false, text = "8 passed in 0.42s"),
        TerminalLine(isPrompt = true,  text = "python todo.py complete 2"),
        TerminalLine(isPrompt = false, text = "Completed: Ship the release"),
        TerminalLine(isPrompt = true,  text = "git add todo.py && git commit -m \"feat: add todo CLI\""),
        TerminalLine(isPrompt = false, text = "[main 4f2a1c3] feat: add todo CLI"),
        TerminalLine(isPrompt = false, text = " 1 file changed, 47 insertions(+)"),
    )

    // -------------------------------------------------------------------------
    // Sessions
    // -------------------------------------------------------------------------

    val sessions: List<ProjectSession> = listOf(
        ProjectSession(
            id = "demo-session-1",
            name = "demo-session-1",
            assistant = "claude",
            branch = null,
            preview = null,
            reasoningEffort = null,
            cwd = "/home/user/projects/todo",
            startedAt = "2026-06-25T10:00:00Z",
            lastActivityAt = "2026-06-25T10:03:30Z",
            displayName = "Build a to-do app",
            totalInputTokens = 120_000UL,
            totalOutputTokens = 18_000UL,
            totalCachedTokens = 90_000UL,
            totalCostUsd = 0.42,
            contextUsedTokens = 48_000UL,
            contextWindowTokens = 200_000UL,
        ),
        ProjectSession(
            id = "demo-session-2",
            name = "demo-session-2",
            assistant = "claude",
            branch = null,
            preview = null,
            reasoningEffort = null,
            cwd = "/home/user/projects/api",
            startedAt = "2026-06-25T09:30:00Z",
            lastActivityAt = "2026-06-25T09:35:00Z",
            displayName = "Fix authentication bug",
            totalInputTokens = 34_000UL,
            totalOutputTokens = 5_200UL,
            totalCachedTokens = 22_000UL,
            totalCostUsd = 0.11,
            contextUsedTokens = 12_000UL,
            contextWindowTokens = 200_000UL,
        ),
    )

    // -------------------------------------------------------------------------
    // Canned SessionStatus for demo sessions
    //
    // Seeded into store.statusBySession by activateDemo() so Usage/Recap/Activity
    // screens light up. Values are consistent with the session usage fields above.
    // -------------------------------------------------------------------------

    val statusBySession: Map<String, SessionStatus> = mapOf(
        "demo-session-1" to SessionStatus(
            session = "demo-session-1",
            assistant = "claude",
            phase = "idle",
            health = "green",
            rows = 40.toUShort(),
            cols = 120.toUShort(),
            yolo = false,
            preview = null,
            sessionName = "demo-session-1",
            viewers = 1u,
            reasoningEffort = null,
            cwd = "/home/user/projects/todo",
            startedAt = "2026-06-25T10:00:00Z",
            lastActivityAt = "2026-06-25T10:03:30Z",
            displayName = "Build a to-do app",
            totalInputTokens = 120_000UL,
            totalOutputTokens = 18_000UL,
            totalCachedTokens = 90_000UL,
            totalCostUsd = 0.42,
            contextUsedTokens = 48_000UL,
            contextWindowTokens = 200_000UL,
        ),
        "demo-session-2" to SessionStatus(
            session = "demo-session-2",
            assistant = "claude",
            phase = "idle",
            health = "green",
            rows = 40.toUShort(),
            cols = 120.toUShort(),
            yolo = false,
            preview = null,
            sessionName = "demo-session-2",
            viewers = 1u,
            reasoningEffort = null,
            cwd = "/home/user/projects/api",
            startedAt = "2026-06-25T09:30:00Z",
            lastActivityAt = "2026-06-25T09:35:00Z",
            displayName = "Fix authentication bug",
            totalInputTokens = 34_000UL,
            totalOutputTokens = 5_200UL,
            totalCachedTokens = 22_000UL,
            totalCostUsd = 0.11,
            contextUsedTokens = 12_000UL,
            contextWindowTokens = 200_000UL,
        ),
    )

    // -------------------------------------------------------------------------
    // Pipelines (Flow demo fixtures)
    //
    // Feeds the demo home FLOWS section (real FlowCard component) and the
    // Monitor's static-fixture seam (PipelineMonitorScreen's `demoStatus`
    // param). No network -- hand-built to mirror the broker's real shapes
    // (see PipelineListScreen.kt / PipelineMonitorScreen.kt). Mirrors iOS
    // DemoData.pipelines / DemoData.pipelineStatus(id:) value-for-value.
    // -------------------------------------------------------------------------

    val pipelines: List<PipelineSummary> = listOf(
        PipelineSummary(
            id = "demo-flow-1",
            title = "Add rate limiter to broker",
            state = "awaiting_gate",
            currentStep = 1,
            stepCount = 3,
            created = "2026-06-25T10:00:00Z",
            steps = listOf(
                PipelineSummaryStep(agent = "claude", role = "research", status = "done", gateAfter = false),
                PipelineSummaryStep(agent = "claude", role = "design", status = "done", gateAfter = true),
                PipelineSummaryStep(agent = "codex", role = "build", status = "queued", gateAfter = false),
            ),
            result = null,
        ),
        PipelineSummary(
            id = "demo-flow-2",
            title = "Migrate settings to KV store",
            state = "running",
            currentStep = 1,
            stepCount = 3,
            created = "2026-06-25T09:30:00Z",
            steps = listOf(
                PipelineSummaryStep(agent = "claude", role = "research", status = "done", gateAfter = false),
                PipelineSummaryStep(agent = "codex", role = "build", status = "running", gateAfter = false),
                PipelineSummaryStep(agent = "codex", role = "verify", status = "queued", gateAfter = false),
            ),
            result = null,
        ),
    )

    /** Gate handoff excerpt shown in the Monitor's "Handoff preview" block for the gated demo fixture. */
    private val flow1GateHandoff = """
        ## Proposed design

        Token-bucket limiter keyed by bearer token:
        - 60 req/min steady, burst 20
        - 429 with Retry-After on exhaustion
        - Metrics counter per client

        Mounted as HTTP middleware ahead of /api/session routes.
    """.trimIndent()

    /** Full per-step detail for the Monitor, keyed by [pipelines] id. Mirrors `GET /api/pipeline/{id}`. */
    fun pipelineStatus(id: String): Pipeline? = when (id) {
        "demo-flow-1" -> Pipeline(
            id = "demo-flow-1",
            title = "Add rate limiter to broker",
            task = "Add rate limiting middleware to the broker's HTTP API to prevent abuse.",
            cwd = "/home/user/projects/broker",
            base = "main",
            state = "awaiting_gate",
            currentStep = 1,
            steps = listOf(
                PipelineStep(
                    index = 0, agentType = "claude", role = "research",
                    promptTemplate = "", inputFromPrev = "", gateAfter = false,
                    sessionId = "demo-flow-1-step-0", phase = "exited(0)",
                    started = "2026-06-25T10:00:00Z", ended = "2026-06-25T10:04:12Z",
                    output = "Reviewed the broker's HTTP middleware chain and existing rate-limit precedent in sibling services. Recommending a token-bucket limiter keyed by client token, mounted ahead of the session routes.",
                ),
                PipelineStep(
                    index = 1, agentType = "claude", role = "design",
                    promptTemplate = "", inputFromPrev = "", gateAfter = true,
                    sessionId = "demo-flow-1-step-1", phase = "exited(0)",
                    started = "2026-06-25T10:04:12Z", ended = "2026-06-25T10:09:47Z",
                    output = flow1GateHandoff,
                ),
                PipelineStep(
                    index = 2, agentType = "codex", role = "build",
                    promptTemplate = "", inputFromPrev = "", gateAfter = false,
                    sessionId = null, phase = null,
                ),
            ),
            gate = PipelineGate(step = 1, prev = flow1GateHandoff, output = flow1GateHandoff),
            result = null,
        )
        "demo-flow-2" -> Pipeline(
            id = "demo-flow-2",
            title = "Migrate settings to KV store",
            task = "Move the app's local settings storage to a KV store backend for durability across reinstalls.",
            cwd = "/home/user/projects/api",
            base = "main",
            state = "running",
            currentStep = 1,
            steps = listOf(
                PipelineStep(
                    index = 0, agentType = "claude", role = "research",
                    promptTemplate = "", inputFromPrev = "", gateAfter = false,
                    sessionId = "demo-flow-2-step-0", phase = "exited(0)",
                    started = "2026-06-25T09:30:00Z", ended = "2026-06-25T09:34:20Z",
                    output = "Audited current settings storage across Settings screens; found 12 keys touching 3 stores. KV store candidate: a boltdb-backed key namespace under ~/.conduit/kv.",
                ),
                PipelineStep(
                    index = 1, agentType = "codex", role = "build",
                    promptTemplate = "", inputFromPrev = "", gateAfter = false,
                    sessionId = "demo-flow-2-step-1", phase = "running",
                    started = "2026-06-25T09:34:20Z", ended = null,
                ),
                PipelineStep(
                    index = 2, agentType = "codex", role = "verify",
                    promptTemplate = "", inputFromPrev = "", gateAfter = false,
                    sessionId = null, phase = null,
                ),
            ),
            gate = null,
            result = null,
        )
        else -> null
    }

    // -------------------------------------------------------------------------
    // Session 1: Build a to-do app
    // -------------------------------------------------------------------------

    private val session1Conversation: List<ConversationItem> = listOf(
        ConversationItem(
            id = "demo-1-1",
            role = "user",
            kind = "message",
            status = "done",
            content = "Build me a simple to-do list app in Python",
            ts = "2026-06-25T10:00:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-2",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "I'll create a clean command-line to-do app. Let me start by creating the file.",
            ts = "2026-06-25T10:00:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-3",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:00:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "python3 -c \"open('todo.py','w').write('...')\"",
            exitCode = 0,
            durationMs = 350UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-4",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:00:15Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Write todo.py",
            exitCode = 0,
            durationMs = 120UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-5",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Done! I've created `todo.py` with `add`, `list`, `complete`, and `delete` commands. Try it with:\n\n```\npython todo.py add 'Buy groceries'\npython todo.py list\n```",
            ts = "2026-06-25T10:00:20Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // PLAN: roadmap the agent lays out after scaffolding the core
        ConversationItem(
            id = "demo-1-plan",
            role = "assistant",
            kind = "plan",
            status = "done",
            content = "Here's the roadmap I'm working through:",
            ts = "2026-06-25T10:00:26Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = listOf(
                PlanStep(text = "scaffold todo.py with a JSON store", state = "done"),
                PlanStep(text = "add / list / complete / delete commands", state = "done"),
                PlanStep(text = "colored output with colorama", state = "todo"),
                PlanStep(text = "unit tests for the CLI commands", state = "todo"),
            ),
        ),
        ConversationItem(
            id = "demo-1-6",
            role = "user",
            kind = "message",
            status = "done",
            content = "Can you add colored output?",
            ts = "2026-06-25T10:02:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-7",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Sure, I'll use `colorama` for cross-platform color support.",
            ts = "2026-06-25T10:02:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-8",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "Collecting colorama\n  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)\nSuccessfully installed colorama-0.4.6",
            ts = "2026-06-25T10:02:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "pip install colorama",
            exitCode = 0,
            durationMs = 1200UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-9",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T10:02:15Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Update todo.py with colorama",
            exitCode = 0,
            durationMs = 90UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-1-10",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Updated! Pending tasks now show in yellow, completed ones in green. Run `python todo.py list` to see it.",
            ts = "2026-06-25T10:02:20Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // CODE: assistant message with a python fenced block
        ConversationItem(
            id = "demo-1-11",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Here is the key section of `todo.py` that handles color output:\n\n```python\nfrom colorama import Fore, Style, init\ninit(autoreset=True)\n\ndef list_tasks(tasks):\n    for i, task in enumerate(tasks, 1):\n        if task['done']:\n            print(f\"{Fore.GREEN}{i}. [x] {task['text']}{Style.RESET_ALL}\")\n        else:\n            print(f\"{Fore.YELLOW}{i}. [ ] {task['text']}{Style.RESET_ALL}\")\n```",
            ts = "2026-06-25T10:02:30Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // DIFF: unified diff of the colorama edit
        ConversationItem(
            id = "demo-1-12",
            role = "tool",
            kind = "diff",
            status = "done",
            content = "--- a/todo.py\n+++ b/todo.py\n@@ -1,5 +1,11 @@\n+from colorama import Fore, Style, init\n+init(autoreset=True)\n+\n import json, sys\n \n def list_tasks(tasks):\n-    for i, task in enumerate(tasks, 1):\n-        print(f\"{i}. {'[x]' if task['done'] else '[ ]'} {task['text']}\")\n+    for i, task in enumerate(tasks, 1):\n+        if task['done']:\n+            print(f\"{Fore.GREEN}{i}. [x] {task['text']}{Style.RESET_ALL}\")\n+        else:\n+            print(f\"{Fore.YELLOW}{i}. [ ] {task['text']}{Style.RESET_ALL}\")",
            ts = "2026-06-25T10:02:35Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = null,
            exitCode = 0,
            durationMs = 90UL,
            diffSummary = "1 file · +6 -1",
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // SUBAGENT: audit of the CLI commands
        ConversationItem(
            id = "demo-1-subagent",
            role = "system",
            kind = "subagent",
            status = "done",
            content = "subagent: audited the CLI commands for edge cases\nChecked add / list / complete / delete; added empty-list and duplicate-title handling, and guarded delete against out-of-range indexes.",
            ts = "2026-06-25T10:02:45Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // HANDOFF: claude -> codex to port the CLI to mobile
        ConversationItem(
            id = "demo-1-handoff",
            role = "assistant",
            kind = "handoff",
            status = "done",
            content = "Core CLI is done, colored, and edge-cases are guarded. Handing the mobile packaging + port to codex.",
            ts = "2026-06-25T10:02:52Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = "claude",
            targetAgent = "codex",
            taskText = "Package the to-do CLI and port it to the mobile app",
            resultSummary = "Core CLI is done, colored, and edge-cases are guarded. Handing the mobile packaging + port to codex.",
            planSteps = emptyList(),
        ),
        // PENDING-INPUT: assistant asking if user wants unit tests
        ConversationItem(
            id = "demo-1-13",
            role = "assistant",
            kind = "pending_input",
            status = "pending",
            content = "Want me to add unit tests for the CLI commands?",
            ts = "2026-06-25T10:03:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = listOf("Add tests", "Not now"),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
    )

    // -------------------------------------------------------------------------
    // Session 2: Fix authentication bug
    // -------------------------------------------------------------------------

    private val session2Conversation: List<ConversationItem> = listOf(
        ConversationItem(
            id = "demo-2-1",
            role = "user",
            kind = "message",
            status = "done",
            content = "My login endpoint returns 401 even with correct credentials",
            ts = "2026-06-25T09:30:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-2",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Let me look at the auth code.",
            ts = "2026-06-25T09:30:05Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-3",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "src/auth.py:47:    if token.expires_at >= now:",
            ts = "2026-06-25T09:30:10Z",
            files = emptyList(),
            toolName = "bash",
            command = "grep -r 'expired_at\\|token' src/auth.py",
            exitCode = 0,
            durationMs = 180UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-4",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Found it -- line 47 uses `>=` instead of `>`, so tokens are rejected exactly at their stated expiry rather than after. Let me fix it.",
            ts = "2026-06-25T09:30:15Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-5",
            role = "tool",
            kind = "tool",
            status = "done",
            content = "",
            ts = "2026-06-25T09:30:20Z",
            files = emptyList(),
            toolName = "str_replace_based_edit_tool",
            command = "Fix auth.py:47 >= to >",
            exitCode = 0,
            durationMs = 80UL,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        ConversationItem(
            id = "demo-2-6",
            role = "assistant",
            kind = "message",
            status = "done",
            content = "Fixed. The comparison is now `> expires_at` instead of `>= expires_at`. Tokens will now be accepted up to and including their expiry second.",
            ts = "2026-06-25T09:30:25Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // PLAN: checklist for the full fix
        ConversationItem(
            id = "demo-2-7",
            role = "assistant",
            kind = "plan",
            status = "done",
            content = "Here is the plan for the full token-refresh fix:",
            ts = "2026-06-25T09:30:30Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = listOf(
                PlanStep(text = "reproduce the 401 loop", state = "done"),
                PlanStep(text = "add backoff on refresh", state = "done"),
                PlanStep(text = "add a regression test", state = "todo"),
            ),
        ),
        // SUBAGENT: audit of refreshToken callers
        ConversationItem(
            id = "demo-2-8",
            role = "system",
            kind = "subagent",
            status = "done",
            content = "subagent: audited callers of refreshToken()\nFound 3 call sites; 2 guarded, 1 missing the 401 backoff.",
            ts = "2026-06-25T09:31:00Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = null,
            targetAgent = null,
            taskText = null,
            resultSummary = null,
            planSteps = emptyList(),
        ),
        // HANDOFF: claude -> codex to port fix to mobile
        ConversationItem(
            id = "demo-2-9",
            role = "assistant",
            kind = "handoff",
            status = "done",
            content = "Refresh loop fixed; 401s now back off. Handing the mobile port to codex.",
            ts = "2026-06-25T09:31:30Z",
            files = emptyList(),
            toolName = null,
            command = null,
            exitCode = null,
            durationMs = null,
            diffSummary = null,
            pendingOptions = emptyList(),
            sourceAgent = "claude",
            targetAgent = "codex",
            taskText = "Port the token-refresh fix to the mobile client",
            resultSummary = "Refresh loop fixed; 401s now back off. Handing the mobile port to codex.",
            planSteps = emptyList(),
        ),
    )

    // -------------------------------------------------------------------------
    // Conversations keyed by session id (declared after the lists to respect
    // Kotlin object-property initialization order — referencing them above
    // would read uninitialized nulls and cause a compile error).
    // -------------------------------------------------------------------------

    val conversationBySession: Map<String, List<ConversationItem>> = mapOf(
        "demo-session-1" to session1Conversation,
        "demo-session-2" to session2Conversation,
    )
}
