package session

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// recap.go — agent-written recap at the top of a resumed Found Session.
//
// When a Found Session is adopted (adopt-resume / adopt-fork), the live agent
// is launched with `--resume <externalID>` (claude) / `exec resume <id>`
// (codex) against the transcript staged into the per-session agent-home, so it
// loads the full prior conversation into its own memory. The Chat tab, however,
// hydrates from the session's conversation.jsonl — which is brand new — so the
// chat would open looking empty/fresh.
//
// We seed conversation.jsonl with ONE short, agent-WRITTEN recap of what the
// prior session was doing, generated by a bounded one-shot model turn against
// the staged transcript. This replaces the older raw 10-entry excerpt
// (seedResumeExcerpt), which dumped noisy mid-flow fragments and
// task-notifications that read poorly as a "what we were doing" review.
//
// Invariant — the live session's --resume must stay pristine. The one-shot
// MUST NOT advance/mutate the transcript the live session will resume:
//   - claude: reads the staged transcript via ExternalTranscript, builds a
//     bounded tail digest, and runs a fresh throwaway `claude --print <digest>`
//     with NO `--resume` / `--fork-session`. This avoids the full transcript
//     re-ingest that caused 45 s timeouts on large sessions (e.g. 172 turns).
//   - codex: `codex exec resume <id>` would APPEND a turn to the staged rollout
//     (codex has no --fork-session), polluting the live resume. So codex does
//     NOT resume — it runs a fresh, throwaway `codex exec --json` over a text
//     digest of the transcript (read via ExternalTranscript), touching no
//     rollout file. If that one-shot fails, codex falls back to the
//     deterministic note like claude does.
//
// Both paths are now: digest-from-ExternalTranscript + fresh non-resume one-shot.
//
// Timing — generateRecap is called SYNCHRONOUSLY in the external-resume setup
// path before the spawn returns, under a bounded context (recapTimeout). A
// fresh digest-based model turn completes in a few seconds (no transcript
// re-ingest). The bound guarantees session creation is never blocked past the
// timeout, and on timeout/error we fall back to the instant deterministic note.
// The recap is written to conversation.jsonl before the spawn returns, so it is
// present at the app's first hydrate (no async re-hydrate needed).

// recapTimeout bounds the one-shot recap model turn. On expiry the caller
// falls back to the deterministic note so resume never blocks/fails.
const recapTimeout = 45 * time.Second

// recapPrompt is the instruction handed to the one-shot model turn.
const recapPrompt = "In 2-3 sentences, recap what this session was working on and where we left off, so I can continue. Be concise; no preamble, no markdown headers."

// generateRecap is the stubbable seam for producing the recap text. Production
// wires generateRecapLive; tests swap in a stub so unit tests never invoke a
// real model. It returns the recap text, or an error (the caller then falls
// back to the deterministic note).
//
// Parameters:
//
//	agent      — "claude" | "codex"
//	externalID — the claude session UUID / codex thread id (for claude --resume)
//	agentHome  — the per-session ephemeral $HOME the staged transcript lives in
//	binary     — the resolved agent CLI binary path ("" → skip, fall back)
var generateRecap = generateRecapLive

// recapBinary resolves the CLI binary path for the recap one-shot of the given
// agent ("claude" | "codex") from the session's registry-resolved binary
// getters. Returns "" when the agent isn't registered — the recap then falls
// back to the deterministic note.
func (s *Session) recapBinary(agent string) string {
	switch agent {
	case "claude":
		if s.claudeBinary != nil {
			return s.claudeBinary()
		}
	case "codex":
		if s.codexBinary != nil {
			return s.codexBinary()
		}
	}
	return ""
}

// seedResumeRecap generates an agent-written recap of the prior external
// transcript and seeds it as a SINGLE system message into the new session's
// conversation.jsonl, so the Chat tab opens showing "what we were doing"
// instead of looking brand-new.
//
// Best-effort + bounded + idempotent:
//   - idempotent: skipped if conversation.jsonl already has content (broker
//     restart re-running newSession).
//   - bounded: the model turn runs under recapTimeout.
//   - never fails the spawn: on any error/timeout it falls back to a
//     deterministic note (session-derived) so the chat still opens with context.
func seedResumeRecap(convLogPath, agent, externalID, agentHome, binary string) {
	if convLogPath == "" || agent == "" || externalID == "" {
		return
	}

	// Idempotency guard up front: if conversation.jsonl is already non-empty
	// (e.g. a broker restart re-ran newSession), don't re-run a model turn or
	// double-seed.
	if info, err := os.Stat(convLogPath); err == nil && info.Size() > 0 {
		log.Printf("found-sessions: seedResumeRecap: conversation.jsonl already has content at %s (skipping)", convLogPath)
		return
	}

	ctx, cancel := context.WithTimeout(context.Background(), recapTimeout)
	defer cancel()

	recap, err := generateRecap(ctx, agent, externalID, agentHome, binary)
	recap = strings.TrimSpace(recap)
	if err != nil || recap == "" {
		if err != nil {
			log.Printf("found-sessions: seedResumeRecap: generateRecap(%s,%s): %v (falling back to deterministic note)", agent, externalID, err)
		} else {
			log.Printf("found-sessions: seedResumeRecap: generateRecap(%s,%s) returned empty (falling back to deterministic note)", agent, externalID)
		}
		recap = deterministicRecap(agent, externalID)
	}

	seedRecapEntry(convLogPath, agent, recap)
}

// seedRecapEntry writes the formatted recap as a SINGLE "system" ConvEntry into
// convLogPath. Idempotent (skips a non-empty file) and the testable core of the
// write/format path: tests call this directly with a stubbed recap string.
//
// Empty recap → no-op (the caller always supplies a non-empty recap or the
// deterministic fallback, but guard defensively).
func seedRecapEntry(convLogPath, agent, recap string) {
	recap = strings.TrimSpace(recap)
	if convLogPath == "" || recap == "" {
		return
	}

	// Idempotency: never seed over an existing conversation.
	if info, err := os.Stat(convLogPath); err == nil && info.Size() > 0 {
		log.Printf("found-sessions: seedRecapEntry: conversation.jsonl already has content at %s (skipping)", convLogPath)
		return
	}

	if mkErr := os.MkdirAll(filepath.Dir(convLogPath), 0o700); mkErr != nil {
		log.Printf("found-sessions: seedRecapEntry: mkdir %s: %v (skipping)", filepath.Dir(convLogPath), mkErr)
		return
	}

	entry := ConvEntry{
		Role:    "system",
		Content: formatRecapMessage(agent, recap),
		Ts:      time.Now().UTC().Format(time.RFC3339Nano),
	}
	b, merr := json.Marshal(entry)
	if merr != nil {
		log.Printf("found-sessions: seedRecapEntry: marshal: %v (skipping)", merr)
		return
	}
	f, openErr := os.OpenFile(convLogPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o600)
	if openErr != nil {
		log.Printf("found-sessions: seedRecapEntry: open %s: %v (skipping)", convLogPath, openErr)
		return
	}
	defer f.Close()
	if _, werr := fmt.Fprintf(f, "%s\n", b); werr != nil {
		log.Printf("found-sessions: seedRecapEntry: write %s: %v", convLogPath, werr)
		return
	}
	log.Printf("found-sessions: seedRecapEntry: seeded recap into %s (agent=%s)", convLogPath, agent)
}

// formatRecapMessage wraps the raw recap text in the framing shown at the top
// of a resumed chat. ONE clear message — not a multi-line raw dump.
func formatRecapMessage(agent, recap string) string {
	return fmt.Sprintf(
		"↩︎ Resumed from your terminal — picking up where you left off:\n\n%s\n\n(The full history is loaded in %s's memory.)",
		strings.TrimSpace(recap), agent,
	)
}

// deterministicRecap is the no-model fallback: a minimal note derived from the
// prior transcript itself (first user prompt + turn count). It NEVER blocks
// (it reads the already-on-disk transcript) and never errors out — on any
// failure it degrades to a bare turn-agnostic line. This guarantees resume
// always seeds SOMETHING useful even when the model one-shot can't run.
func deterministicRecap(agent, externalID string) string {
	all, err := ExternalTranscript(agent, externalID)
	if err != nil || len(all) == 0 {
		return "Resumed a session you started in your terminal. The full history is loaded in the agent's memory."
	}
	first := firstUserPrompt(all)
	turns := len(all)
	if first == "" {
		return fmt.Sprintf("Resumed a session you started in your terminal (%d earlier turns). The full history is loaded in the agent's memory.", turns)
	}
	return fmt.Sprintf("Resumed a session you started in your terminal (%d earlier turns). It began with: %q", turns, first)
}

// firstUserPrompt returns a trimmed, single-line, length-capped version of the
// first user message in the transcript, for the deterministic recap.
func firstUserPrompt(all []ConvEntry) string {
	for _, e := range all {
		if e.Role != "user" {
			continue
		}
		s := strings.TrimSpace(e.Content)
		if s == "" {
			continue
		}
		s = strings.Join(strings.Fields(s), " ") // collapse whitespace/newlines
		const maxLen = 160
		if len(s) > maxLen {
			s = s[:maxLen] + "…"
		}
		return s
	}
	return ""
}

// generateRecapLive runs the bounded one-shot recap model turn. It dispatches
// per agent; both claude and codex summarize a tail digest of the transcript
// via a fresh non-resume one-shot. Returns the recap text or an error.
func generateRecapLive(ctx context.Context, agent, externalID, agentHome, binary string) (string, error) {
	if strings.TrimSpace(binary) == "" {
		return "", fmt.Errorf("recap: no %s binary available", agent)
	}
	switch agent {
	case "claude":
		return claudeRecap(ctx, binary, agentHome, externalID)
	case "codex":
		return codexRecap(ctx, binary, agentHome, externalID)
	default:
		return "", fmt.Errorf("recap: unknown agent %q", agent)
	}
}

// claudeRecap produces a recap WITHOUT resuming the staged transcript. The
// old `--resume <id> --fork-session` approach caused 45 s timeouts on large
// sessions (e.g. 172 turns) because claude re-ingests the entire conversation
// before answering. Instead we read the transcript via ExternalTranscript,
// build a bounded tail digest (same helper as codexRecap), and run a fresh
// throwaway `claude --print <digest+prompt>` — no --resume, no fork, no
// re-ingest. Fast, well under the timeout, and symmetrical with codexRecap.
func claudeRecap(ctx context.Context, binary, agentHome, externalID string) (string, error) {
	all, err := ExternalTranscript("claude", externalID)
	if err != nil || len(all) == 0 {
		if err != nil {
			return "", fmt.Errorf("claudeRecap: ExternalTranscript: %w", err)
		}
		return "", fmt.Errorf("claudeRecap: empty transcript")
	}
	digest := transcriptDigest(all)
	prompt := "Below is the tail of a coding session. In 2-3 sentences, recap what was being worked on and where it left off, so I can continue. Be concise; no preamble.\n\n" + digest

	argv := []string{
		binary,
		"--dangerously-skip-permissions",
		"--print", prompt,
	}
	cmd := exec.CommandContext(ctx, argv[0], argv[1:]...)
	cmd.Env = recapEnv(agentHome)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &limitWriter{w: &stderr, limit: 4096}
	if err := cmd.Run(); err != nil {
		if ctx.Err() != nil {
			return "", fmt.Errorf("claudeRecap: timeout: %w", ctx.Err())
		}
		return "", fmt.Errorf("claudeRecap: %v (%s)", err, firstMeaningfulLine(stderr.String()))
	}
	out := strings.TrimSpace(stdout.String())
	if out == "" {
		return "", fmt.Errorf("claudeRecap: empty output")
	}
	return out, nil
}

// codexRecap produces a recap WITHOUT resuming the staged rollout (codex has no
// --fork-session, so `exec resume` would mutate the file the live session
// resumes). It reads the staged transcript via ExternalTranscript, builds a
// bounded text digest, and runs a fresh throwaway `codex exec --json` over it —
// touching no rollout file.
func codexRecap(ctx context.Context, binary, agentHome, externalID string) (string, error) {
	all, err := ExternalTranscript("codex", externalID)
	if err != nil || len(all) == 0 {
		if err != nil {
			return "", fmt.Errorf("codexRecap: ExternalTranscript: %w", err)
		}
		return "", fmt.Errorf("codexRecap: empty transcript")
	}
	digest := transcriptDigest(all)
	prompt := "Here is a transcript of an earlier coding session:\n\n" + digest +
		"\n\n" + recapPrompt

	argv := []string{binary, "exec", "--json", "--skip-git-repo-check", "-c", "model_reasoning_effort=low", prompt}
	cmd := exec.CommandContext(ctx, argv[0], argv[1:]...)
	cmd.Env = recapEnv(agentHome)

	stdoutPipe, err := cmd.StdoutPipe()
	if err != nil {
		return "", fmt.Errorf("codexRecap: stdout pipe: %w", err)
	}
	var stderr bytes.Buffer
	cmd.Stderr = &limitWriter{w: &stderr, limit: 4096}
	if err := cmd.Start(); err != nil {
		return "", fmt.Errorf("codexRecap: start: %w", err)
	}
	var last string
	sc := bufio.NewScanner(stdoutPipe)
	sc.Buffer(make([]byte, 0, 64*1024), 8*1024*1024)
	for sc.Scan() {
		evs, _, ok := parseCodexStreamLine(sc.Bytes())
		if !ok {
			continue
		}
		for _, e := range evs {
			if e.Role == "assistant" && strings.TrimSpace(e.Text) != "" {
				last = e.Text
			}
		}
	}
	waitErr := cmd.Wait()
	if ctx.Err() != nil {
		return "", fmt.Errorf("codexRecap: timeout: %w", ctx.Err())
	}
	if strings.TrimSpace(last) == "" {
		if waitErr != nil {
			return "", fmt.Errorf("codexRecap: %v (%s)", waitErr, firstMeaningfulLine(stderr.String()))
		}
		return "", fmt.Errorf("codexRecap: no agent message in output")
	}
	return strings.TrimSpace(last), nil
}

// transcriptDigest renders a transcript as a compact role-tagged text block for
// the codex summarization prompt. Caps total length and per-message length so a
// huge transcript can't blow the argv/context budget — the tail (most recent
// turns) is kept since that's where "we left off".
func transcriptDigest(all []ConvEntry) string {
	const (
		maxMsgs   = 40
		maxPerMsg = 600
		maxTotal  = 12000
	)
	entries := all
	if len(entries) > maxMsgs {
		entries = entries[len(entries)-maxMsgs:]
	}
	var b strings.Builder
	for _, e := range entries {
		c := strings.TrimSpace(e.Content)
		if c == "" {
			continue
		}
		if len(c) > maxPerMsg {
			c = c[:maxPerMsg] + "…"
		}
		role := e.Role
		if role == "" {
			role = "unknown"
		}
		fmt.Fprintf(&b, "[%s] %s\n", role, c)
		if b.Len() > maxTotal {
			break
		}
	}
	return strings.TrimSpace(b.String())
}

// recapEnv builds the environment for a one-shot recap exec: the broker env
// with HOME pinned to the per-session agent-home so the staged transcript and
// credentials resolve there (matching the live session's isolation).
func recapEnv(agentHome string) []string {
	env := os.Environ()
	if strings.TrimSpace(agentHome) == "" {
		return env
	}
	out := make([]string, 0, len(env)+1)
	for _, kv := range env {
		if strings.HasPrefix(kv, "HOME=") {
			continue
		}
		out = append(out, kv)
	}
	return append(out, "HOME="+agentHome)
}
